sudo: required
services:
  - docker

before_install:
  - docker build -t  kevin-Polytech/docker-react -f Dockerfile.dev .

script:
  - docker run  kevin-Polytech/docker-react npm run test -- --coverage